require("core.settings")
require("core.globals")
require("core.mappings")
require("core.spec")
require("core.autocmds")

plugin("plugins.color_scheme")
plugin("plugins.color_comments")
plugin("plugins.colorizer")
plugin("plugins.telescope")
plugin("plugins.tree_sitter")
plugin("plugins.accelerated")
plugin("plugins.lsp")

require("core.lazy")
